export interface UniversidadeIntl {
  sigla: string;
  instituicao: string;
  cidade: string;
  estado: string;
  regiao: string;
  tipo: "Public" | "Private" | "Public (State)";
  ranking?: number;
  vagas_ano: number;
  mensalidade_ano: number;
  duracao_anos: number;
  temPosGrad: boolean;
  programasPosGrad?: string[];
  acreditacao: string;
  pontosFocais: string[];
}

// ─────────────────────────────────────────────
// USA — CODA-accredited dental schools (~35 most important)
// ─────────────────────────────────────────────

export const universidadesUSA: UniversidadeIntl[] = [
  {
    sigla: "HSDM",
    instituicao: "Harvard School of Dental Medicine",
    cidade: "Boston",
    estado: "MA",
    regiao: "Northeast",
    tipo: "Private",
    ranking: 1,
    vagas_ano: 35,
    mensalidade_ano: 79460,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Prosthodontics",
      "Periodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Oral Medicine",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Craniofacial Biology",
      "Regenerative Medicine",
      "Oral Oncology",
      "Implantology",
      "Global Oral Health",
    ],
  },
  {
    sigla: "UM-Dent",
    instituicao: "University of Michigan School of Dentistry",
    cidade: "Ann Arbor",
    estado: "MI",
    regiao: "Midwest",
    tipo: "Public",
    ranking: 2,
    vagas_ano: 106,
    mensalidade_ano: 38942,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Pediatric Dentistry",
      "Oral Surgery",
      "Endodontics",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Cariology",
      "Oral Biology",
      "Dental Public Health",
      "Biomaterials",
      "Periodontics Research",
    ],
  },
  {
    sigla: "UCSF-Dent",
    instituicao: "UCSF School of Dentistry",
    cidade: "San Francisco",
    estado: "CA",
    regiao: "West",
    tipo: "Public",
    ranking: 3,
    vagas_ano: 88,
    mensalidade_ano: 35640,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Oral Medicine",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Oral Cancer Research",
      "Craniofacial Genetics",
      "Health Disparities",
      "Digital Dentistry",
      "Biomaterials",
    ],
  },
  {
    sigla: "CUCDM",
    instituicao: "Columbia University College of Dental Medicine",
    cidade: "New York",
    estado: "NY",
    regiao: "Northeast",
    tipo: "Private",
    ranking: 4,
    vagas_ano: 80,
    mensalidade_ano: 88872,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Prosthodontics",
      "Periodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Oral Medicine",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Translational Research",
      "Oral Microbiology",
      "Periodontal Medicine",
      "Craniofacial Development",
      "Global Health",
    ],
  },
  {
    sigla: "Penn-Dental",
    instituicao: "University of Pennsylvania School of Dental Medicine",
    cidade: "Philadelphia",
    estado: "PA",
    regiao: "Northeast",
    tipo: "Private",
    ranking: 5,
    vagas_ano: 112,
    mensalidade_ano: 82648,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Oral Medicine",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Periodontal Immunology",
      "Oral Microbiology",
      "Biomaterials",
      "Oral Cancer",
      "Implant Dentistry",
    ],
  },
  {
    sigla: "NYU-Dent",
    instituicao: "NYU College of Dentistry",
    cidade: "New York",
    estado: "NY",
    regiao: "Northeast",
    tipo: "Private",
    ranking: 6,
    vagas_ano: 370,
    mensalidade_ano: 78980,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Oral Medicine",
      "Dental Public Health",
      "Implantology",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Global Oral Health",
      "Implant Dentistry",
      "Digital Dentistry",
      "Community Dentistry",
      "Aesthetic Dentistry",
    ],
  },
  {
    sigla: "UNC-Adams",
    instituicao: "University of North Carolina Adams School of Dentistry",
    cidade: "Chapel Hill",
    estado: "NC",
    regiao: "South",
    tipo: "Public",
    ranking: 7,
    vagas_ano: 81,
    mensalidade_ano: 24160,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Dental Public Health",
      "Cariology",
      "Periodontics",
      "Oral Epidemiology",
      "Community Oral Health",
    ],
  },
  {
    sigla: "UCLA-Dent",
    instituicao: "UCLA School of Dentistry",
    cidade: "Los Angeles",
    estado: "CA",
    regiao: "West",
    tipo: "Public",
    ranking: 8,
    vagas_ano: 88,
    mensalidade_ano: 35640,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Oral Medicine",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Craniofacial Biology",
      "Oral Oncology",
      "Regenerative Dentistry",
      "Implantology",
      "Digital Dentistry",
    ],
  },
  {
    sigla: "UW-Dent",
    instituicao: "University of Washington School of Dentistry",
    cidade: "Seattle",
    estado: "WA",
    regiao: "West",
    tipo: "Public",
    ranking: 9,
    vagas_ano: 57,
    mensalidade_ano: 36714,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Oral Health Disparities",
      "Dental Informatics",
      "Oral Biology",
      "Periodontics",
      "Pacific Northwest Community Health",
    ],
  },
  {
    sigla: "Tufts-Dent",
    instituicao: "Tufts University School of Dental Medicine",
    cidade: "Boston",
    estado: "MA",
    regiao: "Northeast",
    tipo: "Private",
    ranking: 10,
    vagas_ano: 164,
    mensalidade_ano: 73990,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Oral Medicine",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Geriatric Dentistry",
      "Community Dentistry",
      "Prosthodontics",
      "Implant Dentistry",
      "Oral Health Policy",
    ],
  },
  {
    sigla: "BU-GSDM",
    instituicao: "Boston University Henry M. Goldman School of Dental Medicine",
    cidade: "Boston",
    estado: "MA",
    regiao: "Northeast",
    tipo: "Private",
    ranking: 11,
    vagas_ano: 105,
    mensalidade_ano: 72400,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Oral Medicine",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Implant Dentistry",
      "Prosthodontics",
      "Periodontology",
      "Aesthetic Dentistry",
      "Digital Dentistry",
    ],
  },
  {
    sigla: "UI-Dent",
    instituicao: "University of Iowa College of Dentistry",
    cidade: "Iowa City",
    estado: "IA",
    regiao: "Midwest",
    tipo: "Public",
    ranking: 12,
    vagas_ano: 72,
    mensalidade_ano: 31100,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Cariology",
      "Oral Biology",
      "Rural Oral Health",
      "Dental Biomaterials",
      "Community Dentistry",
    ],
  },
  {
    sigla: "IU-Dent",
    instituicao: "Indiana University School of Dentistry",
    cidade: "Indianapolis",
    estado: "IN",
    regiao: "Midwest",
    tipo: "Public",
    ranking: 13,
    vagas_ano: 106,
    mensalidade_ano: 28506,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Dental Education Research",
      "Oral Health Policy",
      "Cariology",
      "Pediatric Dentistry",
      "Community Oral Health",
    ],
  },
  {
    sigla: "OSU-Dent",
    instituicao: "Ohio State University College of Dentistry",
    cidade: "Columbus",
    estado: "OH",
    regiao: "Midwest",
    tipo: "Public",
    ranking: 14,
    vagas_ano: 102,
    mensalidade_ano: 35798,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Oral Medicine",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Oral Cancer Research",
      "Biomaterials",
      "Dental Informatics",
      "Implantology",
      "Craniofacial Research",
    ],
  },
  {
    sigla: "Pitt-Dent",
    instituicao: "University of Pittsburgh School of Dental Medicine",
    cidade: "Pittsburgh",
    estado: "PA",
    regiao: "Northeast",
    tipo: "Private",
    ranking: 15,
    vagas_ano: 88,
    mensalidade_ano: 67912,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Oral Biology",
      "Craniofacial Genetics",
      "Periodontics",
      "Biomaterials",
      "Dental Research",
    ],
  },
  {
    sigla: "UMN-Dent",
    instituicao: "University of Minnesota School of Dentistry",
    cidade: "Minneapolis",
    estado: "MN",
    regiao: "Midwest",
    tipo: "Public",
    ranking: 16,
    vagas_ano: 96,
    mensalidade_ano: 36660,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Dental Biomaterials",
      "Oral Health Disparities",
      "Digital Dentistry",
      "Implantology",
      "Community Dentistry",
    ],
  },
  {
    sigla: "UTHSA-Dent",
    instituicao: "University of Texas Health Science Center San Antonio – Dental School",
    cidade: "San Antonio",
    estado: "TX",
    regiao: "Southwest",
    tipo: "Public",
    ranking: 17,
    vagas_ano: 96,
    mensalidade_ano: 22460,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Hispanic Oral Health",
      "Community Dentistry",
      "Oral Biology",
      "Geriatric Dentistry",
      "Dental Public Health",
    ],
  },
  {
    sigla: "UF-Dent",
    instituicao: "University of Florida College of Dentistry",
    cidade: "Gainesville",
    estado: "FL",
    regiao: "South",
    tipo: "Public",
    ranking: 18,
    vagas_ano: 85,
    mensalidade_ano: 27184,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Oral Cancer Research",
      "Geriatric Dentistry",
      "Oral Biology",
      "Community Health",
      "Periodontics",
    ],
  },
  {
    sigla: "CWRU-Dent",
    instituicao: "Case Western Reserve University School of Dental Medicine",
    cidade: "Cleveland",
    estado: "OH",
    regiao: "Midwest",
    tipo: "Private",
    ranking: 19,
    vagas_ano: 82,
    mensalidade_ano: 69800,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Oral Medicine",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Craniofacial Research",
      "Oral Biology",
      "Biomaterials",
      "Dental Informatics",
      "Translational Research",
    ],
  },
  {
    sigla: "Temple-Dent",
    instituicao: "Temple University Kornberg School of Dentistry",
    cidade: "Philadelphia",
    estado: "PA",
    regiao: "Northeast",
    tipo: "Private",
    ranking: 20,
    vagas_ano: 140,
    mensalidade_ano: 65240,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Urban Community Dentistry",
      "Oral Health Disparities",
      "Periodontics",
      "Dental Education",
      "Implant Dentistry",
    ],
  },
  {
    sigla: "MU-Dent",
    instituicao: "Marquette University School of Dentistry",
    cidade: "Milwaukee",
    estado: "WI",
    regiao: "Midwest",
    tipo: "Private",
    ranking: 21,
    vagas_ano: 80,
    mensalidade_ano: 60972,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Dental Education",
      "Community Oral Health",
      "Prosthodontics",
      "Oral Biology",
      "Cariology",
    ],
  },
  {
    sigla: "LLU-Dent",
    instituicao: "Loma Linda University School of Dentistry",
    cidade: "Loma Linda",
    estado: "CA",
    regiao: "West",
    tipo: "Private",
    ranking: 22,
    vagas_ano: 86,
    mensalidade_ano: 54292,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "International Dental Health",
      "Implantology",
      "Pediatric Dentistry",
      "Community Service",
      "Oral Surgery",
    ],
  },
  {
    sigla: "MUSC-CDM",
    instituicao: "Medical University of South Carolina College of Dental Medicine",
    cidade: "Charleston",
    estado: "SC",
    regiao: "South",
    tipo: "Public",
    ranking: 23,
    vagas_ano: 48,
    mensalidade_ano: 36432,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Rural Oral Health",
      "Oral Cancer",
      "Community Dentistry",
      "Geriatric Dentistry",
      "Periodontics",
    ],
  },
  {
    sigla: "UIC-Dent",
    instituicao: "University of Illinois Chicago College of Dentistry",
    cidade: "Chicago",
    estado: "IL",
    regiao: "Midwest",
    tipo: "Public",
    ranking: 24,
    vagas_ano: 75,
    mensalidade_ano: 38600,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Urban Oral Health",
      "Health Disparities",
      "Oral Biology",
      "Community Dentistry",
      "Dental Biomaterials",
    ],
  },
  {
    sigla: "UL-Dent",
    instituicao: "University of Louisville School of Dentistry",
    cidade: "Louisville",
    estado: "KY",
    regiao: "South",
    tipo: "Public",
    ranking: 25,
    vagas_ano: 98,
    mensalidade_ano: 30880,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Community Oral Health",
      "Rural Dentistry",
      "Oral Biology",
      "Cariology",
      "Periodontics",
    ],
  },
  {
    sigla: "WVU-Dent",
    instituicao: "West Virginia University School of Dentistry",
    cidade: "Morgantown",
    estado: "WV",
    regiao: "South",
    tipo: "Public",
    ranking: 26,
    vagas_ano: 48,
    mensalidade_ano: 25900,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Rural Oral Health",
      "Appalachian Community Health",
      "Dental Public Health",
      "Oral Biology",
      "Community Dentistry",
    ],
  },
  {
    sigla: "UAB-Dent",
    instituicao: "University of Alabama School of Dentistry",
    cidade: "Birmingham",
    estado: "AL",
    regiao: "South",
    tipo: "Public",
    ranking: 27,
    vagas_ano: 56,
    mensalidade_ano: 22920,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Rural Community Dentistry",
      "Oral Health Disparities",
      "Pediatric Dentistry",
      "Oral Biology",
      "Dental Public Health",
    ],
  },
  {
    sigla: "OU-Dent",
    instituicao: "University of Oklahoma College of Dentistry",
    cidade: "Oklahoma City",
    estado: "OK",
    regiao: "Southwest",
    tipo: "Public",
    ranking: 28,
    vagas_ano: 50,
    mensalidade_ano: 22360,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Native American Oral Health",
      "Rural Dentistry",
      "Community Oral Health",
      "Oral Biology",
      "Dental Public Health",
    ],
  },
  {
    sigla: "UNLV-SDM",
    instituicao: "University of Nevada Las Vegas School of Dental Medicine",
    cidade: "Las Vegas",
    estado: "NV",
    regiao: "West",
    tipo: "Public",
    ranking: 29,
    vagas_ano: 75,
    mensalidade_ano: 36000,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Underserved Community Dentistry",
      "Hispanic Oral Health",
      "Geriatric Dentistry",
      "Digital Dentistry",
      "Community Health",
    ],
  },
  {
    sigla: "MMC-Dent",
    instituicao: "Meharry Medical College School of Dentistry",
    cidade: "Nashville",
    estado: "TN",
    regiao: "South",
    tipo: "Private",
    ranking: 30,
    vagas_ano: 50,
    mensalidade_ano: 52100,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Minority Oral Health",
      "Health Disparities",
      "Community Dentistry",
      "Oral Biology",
      "Dental Public Health",
    ],
  },
  // Additional notable schools to reach ~35
  {
    sigla: "Creighton-Dent",
    instituicao: "Creighton University School of Dentistry",
    cidade: "Omaha",
    estado: "NE",
    regiao: "Midwest",
    tipo: "Private",
    ranking: 31,
    vagas_ano: 70,
    mensalidade_ano: 58460,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Rural Oral Health",
      "Community Dentistry",
      "Geriatric Dentistry",
      "Oral Biology",
      "Dental Education",
    ],
  },
  {
    sigla: "USC-Dent",
    instituicao: "University of Southern California Herman Ostrow School of Dentistry",
    cidade: "Los Angeles",
    estado: "CA",
    regiao: "West",
    tipo: "Private",
    ranking: 32,
    vagas_ano: 140,
    mensalidade_ano: 76972,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Oral Medicine",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Craniofacial Biology",
      "Implant Dentistry",
      "Digital Dentistry",
      "Aesthetic Dentistry",
      "International Dental Education",
    ],
  },
  {
    sigla: "Georgetown-Dent",
    instituicao: "Georgetown University School of Dentistry",
    cidade: "Washington",
    estado: "DC",
    regiao: "Northeast",
    tipo: "Private",
    ranking: 33,
    vagas_ano: 75,
    mensalidade_ano: 77160,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Global Health",
      "Community Dentistry",
      "Oral Biology",
      "Implantology",
      "Dental Research",
    ],
  },
  {
    sigla: "Rutgers-SDM",
    instituicao: "Rutgers School of Dental Medicine",
    cidade: "Newark",
    estado: "NJ",
    regiao: "Northeast",
    tipo: "Public",
    ranking: 34,
    vagas_ano: 80,
    mensalidade_ano: 39500,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
      "Dental Public Health",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Urban Oral Health",
      "Community Dentistry",
      "Oral Biology",
      "Health Disparities",
      "Dental Public Health",
    ],
  },
  {
    sigla: "UConn-Dent",
    instituicao: "University of Connecticut School of Dental Medicine",
    cidade: "Farmington",
    estado: "CT",
    regiao: "Northeast",
    tipo: "Public",
    ranking: 35,
    vagas_ano: 44,
    mensalidade_ano: 37000,
    duracao_anos: 4,
    temPosGrad: true,
    programasPosGrad: [
      "Orthodontics",
      "Periodontics",
      "Prosthodontics",
      "Oral Surgery",
      "Pediatric Dentistry",
      "Endodontics",
    ],
    acreditacao: "CODA",
    pontosFocais: [
      "Oral Biology",
      "Craniofacial Research",
      "Biomaterials",
      "Community Dentistry",
      "Dental Public Health",
    ],
  },
];

// ─────────────────────────────────────────────
// Germany — Universitätszahnkliniken (30 public dental schools)
// All free (only Semesterbeitrag ~€350/semester → ~€700/year)
// Degree: Staatsexamen (5 years), accredited under ZÄPrO
// ─────────────────────────────────────────────

const posGradDE = [
  "Kieferorthopädie",
  "Oralchirurgie",
  "Parodontologie",
  "Prothetik",
  "Endodontie",
  "Kinderzahnheilkunde",
];

export const universidadesDE: UniversidadeIntl[] = [
  {
    sigla: "Charité-ZMK",
    instituicao: "Charité – Universitätsmedizin Berlin",
    cidade: "Berlin",
    estado: "Berlin",
    regiao: "Ost",
    tipo: "Public (State)",
    ranking: 1,
    vagas_ano: 65,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Implantologie",
      "Parodontologie",
      "Oralmedizin",
      "Kieferchirurgie",
      "Digitale Zahnmedizin",
    ],
  },
  {
    sigla: "LMU-ZMK",
    instituicao: "LMU München – Poliklinik für Zahnerhaltung",
    cidade: "München",
    estado: "Bayern",
    regiao: "Süd",
    tipo: "Public (State)",
    ranking: 2,
    vagas_ano: 76,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Kieferorthopädie",
      "Parodontologie",
      "Orale Implantologie",
      "Biomaterialien",
      "Oralchirurgie",
    ],
  },
  {
    sigla: "Heidelberg-ZMK",
    instituicao: "Universität Heidelberg – Poliklinik für Zahnheilkunde",
    cidade: "Heidelberg",
    estado: "Baden-Württemberg",
    regiao: "Süd",
    tipo: "Public (State)",
    ranking: 3,
    vagas_ano: 52,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Orale Onkologie",
      "Kieferorthopädie",
      "Parodontologie",
      "Prothetik",
      "Zahnerhaltung",
    ],
  },
  {
    sigla: "UHH-ZMK",
    instituicao: "Universität Hamburg – Universitätsklinikum Hamburg-Eppendorf ZMK",
    cidade: "Hamburg",
    estado: "Hamburg",
    regiao: "Nord",
    tipo: "Public (State)",
    ranking: 4,
    vagas_ano: 60,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Implantologie",
      "Ästhetische Zahnmedizin",
      "Parodontologie",
      "Digitale Zahntechnik",
      "Präventionszahnmedizin",
    ],
  },
  {
    sigla: "Goethe-ZMK",
    instituicao: "Goethe-Universität Frankfurt – Carolinum Zahnärztliches Universitäts-Institut",
    cidade: "Frankfurt",
    estado: "Hessen",
    regiao: "Mitte",
    tipo: "Public (State)",
    ranking: 5,
    vagas_ano: 55,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Kieferorthopädie",
      "Oralchirurgie",
      "Endodontie",
      "Biomaterialforschung",
      "Präventivzahnmedizin",
    ],
  },
  {
    sigla: "UFR-ZMK",
    instituicao: "Universität Freiburg – Universitätszahnklinik",
    cidade: "Freiburg",
    estado: "Baden-Württemberg",
    regiao: "Süd",
    tipo: "Public (State)",
    ranking: 6,
    vagas_ano: 48,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Regenerative Zahnmedizin",
      "Parodontologie",
      "Orale Implantologie",
      "Prothetik",
      "Kieferorthopädie",
    ],
  },
  {
    sigla: "UKöln-ZMK",
    instituicao: "Universität zu Köln – Zentrum für Zahn-, Mund- und Kieferheilkunde",
    cidade: "Köln",
    estado: "Nordrhein-Westfalen",
    regiao: "West",
    tipo: "Public (State)",
    ranking: 7,
    vagas_ano: 67,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Mund-Kiefer-Gesichtschirurgie",
      "Parodontologie",
      "Prothetik",
      "Digitale Zahnmedizin",
      "Kieferorthopädie",
    ],
  },
  {
    sigla: "UBonn-ZMK",
    instituicao: "Rheinische Friedrich-Wilhelms-Universität Bonn – Polikliniken für Zahn-, Mund- und Kieferheilkunde",
    cidade: "Bonn",
    estado: "Nordrhein-Westfalen",
    regiao: "West",
    tipo: "Public (State)",
    ranking: 8,
    vagas_ano: 56,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Orale Mikrobiologie",
      "Zahnerhaltung",
      "Kieferorthopädie",
      "Prothetik",
      "Oralchirurgie",
    ],
  },
  {
    sigla: "RWTH-ZMK",
    instituicao: "RWTH Aachen – Klinik für Zahnerhaltung, Parodontologie und Präventive Zahnheilkunde",
    cidade: "Aachen",
    estado: "Nordrhein-Westfalen",
    regiao: "West",
    tipo: "Public (State)",
    ranking: 9,
    vagas_ano: 40,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Biomaterialien",
      "Digitale Zahnheilkunde",
      "Parodontologie",
      "Prothetik",
      "Zahnmedizinische Werkstoffkunde",
    ],
  },
  {
    sigla: "UDüss-ZMK",
    instituicao: "Heinrich-Heine-Universität Düsseldorf – Westdeutsche Kieferklinik",
    cidade: "Düsseldorf",
    estado: "Nordrhein-Westfalen",
    regiao: "West",
    tipo: "Public (State)",
    ranking: 10,
    vagas_ano: 55,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Implantologie",
      "Parodontologie",
      "Orale Rehabilitation",
      "Kieferorthopädie",
      "Mund-Kiefer-Gesichtschirurgie",
    ],
  },
  {
    sigla: "FSU-ZMK",
    instituicao: "Friedrich-Schiller-Universität Jena – Poliklinik für Zahnärztliche Prothetik",
    cidade: "Jena",
    estado: "Thüringen",
    regiao: "Ost",
    tipo: "Public (State)",
    ranking: 11,
    vagas_ano: 48,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Prothetik",
      "Biomaterialien",
      "Parodontologie",
      "Endodontie",
      "Zahntechnik",
    ],
  },
  {
    sigla: "ULeipzig-ZMK",
    instituicao: "Universität Leipzig – Poliklinik für Zahnerhaltung und Parodontologie",
    cidade: "Leipzig",
    estado: "Sachsen",
    regiao: "Ost",
    tipo: "Public (State)",
    ranking: 12,
    vagas_ano: 52,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Zahnerhaltung",
      "Parodontologie",
      "Orale Chirurgie",
      "Kieferorthopädie",
      "Digitale Prothetik",
    ],
  },
  {
    sigla: "TUD-ZMK",
    instituicao: "Technische Universität Dresden – Universitätszahnmedizin",
    cidade: "Dresden",
    estado: "Sachsen",
    regiao: "Ost",
    tipo: "Public (State)",
    ranking: 13,
    vagas_ano: 45,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Digitale Zahnmedizin",
      "CAD/CAM-Technologie",
      "Implantologie",
      "Biomaterialien",
      "Prothetik",
    ],
  },
  {
    sigla: "UGreifs-ZMK",
    instituicao: "Universität Greifswald – Poliklinik für Zahnerhaltung, Parodontologie und Kinderzahnheilkunde",
    cidade: "Greifswald",
    estado: "Mecklenburg-Vorpommern",
    regiao: "Nord",
    tipo: "Public (State)",
    ranking: 14,
    vagas_ano: 35,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Epidemiologie",
      "Präventivzahnmedizin",
      "Kinderzahnheilkunde",
      "Orale Gesundheit",
      "Community Dentistry",
    ],
  },
  {
    sigla: "URostock-ZMK",
    instituicao: "Universität Rostock – Zentrum für Zahn-, Mund- und Kieferheilkunde",
    cidade: "Rostock",
    estado: "Mecklenburg-Vorpommern",
    regiao: "Nord",
    tipo: "Public (State)",
    ranking: 15,
    vagas_ano: 38,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Parodontologie",
      "Implantologie",
      "Oralchirurgie",
      "Prothetik",
      "Zahnerhaltung",
    ],
  },
  {
    sigla: "MLU-ZMK",
    instituicao: "Martin-Luther-Universität Halle-Wittenberg – Universitätspoliklinik für Zahnerhaltungskunde",
    cidade: "Halle",
    estado: "Sachsen-Anhalt",
    regiao: "Ost",
    tipo: "Public (State)",
    ranking: 16,
    vagas_ano: 44,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Zahnerhaltung",
      "Präventivzahnmedizin",
      "Prothetik",
      "Parodontologie",
      "Kieferorthopädie",
    ],
  },
  {
    sigla: "UGö-ZMK",
    instituicao: "Georg-August-Universität Göttingen – Abteilung Präventive Zahnmedizin, Parodontologie und Kariologie",
    cidade: "Göttingen",
    estado: "Niedersachsen",
    regiao: "Nord",
    tipo: "Public (State)",
    ranking: 17,
    vagas_ano: 52,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Kariologie",
      "Präventivzahnmedizin",
      "Parodontologie",
      "Prothetik",
      "Kieferorthopädie",
    ],
  },
  {
    sigla: "MHH-ZMK",
    instituicao: "Medizinische Hochschule Hannover – Klinik für Zahnerhaltung, Parodontologie und Präventive Zahnheilkunde",
    cidade: "Hannover",
    estado: "Niedersachsen",
    regiao: "Nord",
    tipo: "Public (State)",
    ranking: 18,
    vagas_ano: 50,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Orale Implantologie",
      "Parodontologie",
      "Zahnerhaltung",
      "Biomaterialien",
      "Kieferchirurgie",
    ],
  },
  {
    sigla: "FAU-ZMK",
    instituicao: "Friedrich-Alexander-Universität Erlangen-Nürnberg – Zahnklinik",
    cidade: "Erlangen",
    estado: "Bayern",
    regiao: "Süd",
    tipo: "Public (State)",
    ranking: 19,
    vagas_ano: 58,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Digitale Zahnmedizin",
      "Parodontologie",
      "Prothetik",
      "Oralchirurgie",
      "Kieferorthopädie",
    ],
  },
  {
    sigla: "URegens-ZMK",
    instituicao: "Universität Regensburg – Poliklinik für Kieferorthopädie",
    cidade: "Regensburg",
    estado: "Bayern",
    regiao: "Süd",
    tipo: "Public (State)",
    ranking: 20,
    vagas_ano: 48,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Kieferorthopädie",
      "Parodontologie",
      "Endodontie",
      "Prothetik",
      "Orale Chirurgie",
    ],
  },
  {
    sigla: "UWürz-ZMK",
    instituicao: "Julius-Maximilians-Universität Würzburg – Poliklinik für Zahnerhaltung und Parodontologie",
    cidade: "Würzburg",
    estado: "Bayern",
    regiao: "Süd",
    tipo: "Public (State)",
    ranking: 21,
    vagas_ano: 52,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Zahnerhaltung",
      "Parodontologie",
      "Implantologie",
      "Biomaterialien",
      "Oralchirurgie",
    ],
  },
  {
    sigla: "UTüb-ZMK",
    instituicao: "Eberhard Karls Universität Tübingen – Sektion Parodontologie",
    cidade: "Tübingen",
    estado: "Baden-Württemberg",
    regiao: "Süd",
    tipo: "Public (State)",
    ranking: 22,
    vagas_ano: 50,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Parodontologie",
      "Implantologie",
      "Kieferorthopädie",
      "Ästhetische Zahnmedizin",
      "Prothetik",
    ],
  },
  {
    sigla: "UMünster-ZMK",
    instituicao: "Westfälische Wilhelms-Universität Münster – Poliklinik für Zahnerhaltung",
    cidade: "Münster",
    estado: "Nordrhein-Westfalen",
    regiao: "West",
    tipo: "Public (State)",
    ranking: 23,
    vagas_ano: 60,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Orale Biologie",
      "Parodontologie",
      "Zahnerhaltung",
      "Prothetik",
      "Kieferorthopädie",
    ],
  },
  {
    sigla: "UBochum-ZMK",
    instituicao: "Ruhr-Universität Bochum – Abteilung für Zahnerhaltung und Präventive Zahnmedizin",
    cidade: "Bochum",
    estado: "Nordrhein-Westfalen",
    regiao: "West",
    tipo: "Public (State)",
    ranking: 24,
    vagas_ano: 55,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Präventivzahnmedizin",
      "Kariologie",
      "Parodontologie",
      "Endodontie",
      "Digitale Zahntechnik",
    ],
  },
  {
    sigla: "UMainz-ZMK",
    instituicao: "Johannes Gutenberg-Universität Mainz – Poliklinik für Zahnerhaltungskunde",
    cidade: "Mainz",
    estado: "Rheinland-Pfalz",
    regiao: "Mitte",
    tipo: "Public (State)",
    ranking: 25,
    vagas_ano: 48,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Zahnerhaltung",
      "Endodontie",
      "Parodontologie",
      "Biomaterialien",
      "Oralchirurgie",
    ],
  },
  {
    sigla: "UMarburg-ZMK",
    instituicao: "Philipps-Universität Marburg – Abteilung für Parodontologie",
    cidade: "Marburg",
    estado: "Hessen",
    regiao: "Mitte",
    tipo: "Public (State)",
    ranking: 26,
    vagas_ano: 44,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Parodontologie",
      "Kieferorthopädie",
      "Prothetik",
      "Zahnerhaltung",
      "Orale Rehabilitation",
    ],
  },
  {
    sigla: "CAU-ZMK",
    instituicao: "Christian-Albrechts-Universität zu Kiel – Klinik für Kieferorthopädie",
    cidade: "Kiel",
    estado: "Schleswig-Holstein",
    regiao: "Nord",
    tipo: "Public (State)",
    ranking: 27,
    vagas_ano: 46,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Kieferorthopädie",
      "Implantologie",
      "Parodontologie",
      "Oralchirurgie",
      "Digitale Zahnmedizin",
    ],
  },
  {
    sigla: "UdS-ZMK",
    instituicao: "Universität des Saarlandes – Klinik für Zahnerhaltung, Parodontologie und Präventive Zahnheilkunde",
    cidade: "Homburg",
    estado: "Saarland",
    regiao: "West",
    tipo: "Public (State)",
    ranking: 28,
    vagas_ano: 40,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Zahnerhaltung",
      "Parodontologie",
      "Prothetik",
      "Orale Chirurgie",
      "Kieferorthopädie",
    ],
  },
  {
    sigla: "UUlm-ZMK",
    instituicao: "Universität Ulm – Klinik für Zahnerhaltungskunde und Parodontologie",
    cidade: "Ulm",
    estado: "Baden-Württemberg",
    regiao: "Süd",
    tipo: "Public (State)",
    ranking: 29,
    vagas_ano: 42,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Biomaterialien",
      "Digitale Zahntechnik",
      "Parodontologie",
      "Endodontie",
      "Implantologie",
    ],
  },
  {
    sigla: "JLU-ZMK",
    instituicao: "Justus-Liebig-Universität Giessen – Poliklinik für Kieferorthopädie",
    cidade: "Giessen",
    estado: "Hessen",
    regiao: "Mitte",
    tipo: "Public (State)",
    ranking: 30,
    vagas_ano: 44,
    mensalidade_ano: 700,
    duracao_anos: 5,
    temPosGrad: true,
    programasPosGrad: posGradDE,
    acreditacao: "ZÄPrO",
    pontosFocais: [
      "Kieferorthopädie",
      "Parodontologie",
      "Oralchirurgie",
      "Zahnerhaltung",
      "Prothetik",
    ],
  },
];

// ─────────────────────────────────────────────
// Summary indicators
// ─────────────────────────────────────────────

export const indicadoresUniversidadesUSA = {
  totalEscolas: 67,
  escolasPublicas: 38,
  escolasPrivadas: 29,
  totalVagasAno: 5800,
  mensalidadeMediaPublica: 30500,   // USD/year (in-state)
  mensalidadeMediaPrivada: 71200,   // USD/year
  duracaoMedia: 4,                  // years (after BS degree)
  acreditadora: "CODA (Commission on Dental Accreditation)",
  fonteAnno: "ADEA / US News 2024",
};

export const indicadoresUniversidadesDE = {
  totalEscolas: 30,
  escolasPublicas: 30,
  escolasPrivadas: 0,
  totalVagasAno: 1520,
  mensalidadeMediaPublica: 700,     // EUR/year (Semesterbeitrag)
  mensalidadeMediaPrivada: 0,
  duracaoMedia: 5,                  // years (Staatsexamen)
  acreditadora: "ZÄPrO (Zahnärztliche Approbationsordnung)",
  fonteAnno: "BZÄK / Hochschulkompass 2023",
};

export const formacaoRegionalUSA = [
  { regiao: "Northeast", escolas: 14, vagas: 1580, mensalidade_media: 62000 },
  { regiao: "South",     escolas: 18, vagas: 1420, mensalidade_media: 38000 },
  { regiao: "Midwest",   escolas: 16, vagas: 1380, mensalidade_media: 40000 },
  { regiao: "West",      escolas: 12, vagas: 980,  mensalidade_media: 48000 },
  { regiao: "Southwest", escolas: 7,  vagas: 440,  mensalidade_media: 35000 },
];

export const formacaoRegionalDE = [
  { regiao: "Süd",   escolas: 9, vagas: 424, mensalidade_media: 700 },
  { regiao: "West",  escolas: 7, vagas: 373, mensalidade_media: 700 },
  { regiao: "Nord",  escolas: 6, vagas: 281, mensalidade_media: 700 },
  { regiao: "Ost",   escolas: 5, vagas: 244, mensalidade_media: 700 },
  { regiao: "Mitte", escolas: 3, vagas: 136, mensalidade_media: 700 },
];
